Iter13
AlexCorn999/short-url-service pull request #15
Opened 2023-09-05 04:35 UTC by AlexCorn999

2023-09-05 18:19 UTC, popoffvg requested changes

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +	Store    *bolt.DB
[major]

Одна структура не должна совмещать в себе 2 ответсенности:
- хранение в памяти
- хранение в БД 

Если хотел сделать хранение в БД и кеш в памяти следовало явно выделить две реализации хранилища, реализующий один интерфейс, и адаптер который между ними осущесвтляет маршрутизацию

При этом структуры лучше располагать в разных пакетах

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +	db, err := pgx.Connect(context.Background(), addr)
[minor]
Лучше все конструкторы называть с New

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +	_, err := d.dataBase.Exec(context.Background(), "create table url(id varchar(255) not null, shorturl varchar(255) not null unique, originalurl varchar(255) not null)")
[major]

Стоит пользоваться библиотеками для накатывания миграция (goose, golang-migrate). 
Или как минимум использовать `IF NOT EXISTS` для того чтобы накатка миграции не вызывало ошибок.

Тогда следующий метод не нужен будет

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +func (d *DB) AddURL(url *URL, ssh string) (string, error) {
[major]

В сигнатуре должен быть контекст (обычно получаем из запроса) и с этим контекстом должен выполняться запрос

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +	_, err := d.dataBase.Exec(context.Background(), "create table url(id varchar(255) not null, shorturl varchar(255) not null unique, originalurl varchar(255) not null)")
[major]

id должен быть помечен как первичный ключ явно

2023-09-05 18:19 UTC, popoffvg commented on internal/app/store/db.go
> +	rows, err := d.dataBase.Query(context.Background(), "select shorturl from url where id = $1", ssh)
[minor]

Лучше поспользоваться конструкцией Select, которая вернет одно значение

2023-09-05 18:19 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +			if err.Error() == "URL already exists in the database" {
[major]

Следует объявить в слое с бизнес-логикой глобальную переменную с ошибкой и возвращать ошибку из БД. А здесь проверять ошибку с помощью errors.Is.
```
var ErrConfilict = errors.New("already exists")
```

Недопустимо сравнивать ошибки на `==`

2023-09-05 18:19 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +				store.BackID(&store.IDStorage)
[major]

Реализация генерации id сделана не потокобезопасно. Лучше доверить генерацию id-ников БД.

2023-09-05 18:19 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +	if s.typeStore == "database" {
[major]

Выбор реализации храналища необходимо делать при инициализации хендлера / сервера, а не каждый раз при запросе

2023-09-06 10:18 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +	if s.typeStore == "database" {
Выбор реализации сделал при configureStore()

2023-09-06 10:19 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +				store.BackID(&store.IDStorage)
При работе с БД теперь primary key генерируется и присваивается id

2023-09-06 10:19 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +			if err.Error() == "URL already exists in the database" {
Выполнил

2023-09-06 10:19 UTC, AlexCorn999 commented on internal/app/store/db.go
> +	rows, err := d.dataBase.Query(context.Background(), "select shorturl from url where id = $1", ssh)
Исправил)

2023-09-06 10:19 UTC, AlexCorn999 commented on internal/app/store/db.go
> +	_, err := d.dataBase.Exec(context.Background(), "create table url(id varchar(255) not null, shorturl varchar(255) not null unique, originalurl varchar(255) not null)")
Сделал миграции через goose. Кода стало меньше)

2023-09-06 10:20 UTC, AlexCorn999 commented on internal/app/store/db.go
> +	db, err := pgx.Connect(context.Background(), addr)
Исправил

2023-09-06 10:20 UTC, AlexCorn999 commented on internal/app/store/db.go
> +	Store    *bolt.DB
Переделал весь код. Теперь использую интерфейс и при конфигурации присваиваю необходимую структуру БД.

2023-09-08 05:58 UTC, popoffvg approved these changes

2023-09-08 05:58 UTC, popoffvg commented on internal/app/memorystorage/memorystorage.go
> +func (m *MemoryStorage) WriteURL(url *store.URL, ssh *string) error {
[minor]

Не стоит передавать строку по указателю, т.к. это потенциальная паника и указатель в данном случае не влияет на производительность. 

Стратегия по умолчанию - передавать по значению для всех типов. 
В случае необходимости изменений или после бенчмарков (и только после них) стоит менять на указатель

2023-09-08 05:58 UTC, popoffvg commented on internal/app/store/db.go
> +		fmt.Println(err)
[minor]

Стоит пользоваться структурованными логгерами (zap, lorgus, slog)

2023-09-08 05:58 UTC, popoffvg commented on internal/app/memorystorage/memorystorage.go
> +	m.store[*ssh] = string(data)
[minor]

При || записи в мапу будет лететь паника

2023-09-08 06:20 UTC, merged