Iter15
AlexCorn999/short-url-service pull request #18
Opened 2023-09-27 11:15 UTC by AlexCorn999

2023-09-30 07:21 UTC, popoffvg requested changes

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +		if s.typeStore == "database" {
[major]

В слое контроллеров не должно быть условий, провряющий различные варианты хранилища.

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +			auth.ID = newIDForDB + 1
[major]

Не потокобезопасное обращение к глобальной переменной. При нескольких пользователях корректно работать не будет.

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +			if err == http.ErrNoCookie {
[major]

Недопустимо сравнивать ошибки через `==`. Следует использовать `errors.Is`

2023-09-30 07:21 UTC, popoffvg commented on internal/app/filestorage/filestorage.go
> +				return err
[major]

Ошибки из сторонних библиотек необходимо оборачивать

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +		w.WriteHeader(http.StatusBadRequest)
[major]

При ошибки БД не может быть статуса 400. В случае проблем с сетевеой связностью между сервисом и бд должна возвращаться ошибка 500.

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +			w.WriteHeader(http.StatusBadRequest)
[major]

Должен быть статус 401. Применение правильных статусов ответа очень важно, т.к. позволяет клиента АПИ понять причину проблемы, а службам мониторинга реагировать только на проблемы

2023-09-30 07:21 UTC, popoffvg commented on internal/app/apiserver/apiserver.go
> +				Value: token,
[major]

Для куки с токенами обазятельно устанавливать флаг httpOnly. Если не установить, то при xss атаке на сайт токен может попасть в руки к злоумышленникам.

2023-10-01 09:24 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +			if err == http.ErrNoCookie {
Done  ✅

2023-10-01 09:27 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +		w.WriteHeader(http.StatusBadRequest)
Done ✅

2023-10-01 09:28 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +			w.WriteHeader(http.StatusBadRequest)
Done ✅

2023-10-01 09:29 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +				Value: token,
Спасибо за замечание. Не знал этого момента) Done ✅

2023-10-01 10:02 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +		if s.typeStore == "database" {
Done ✅

2023-10-01 10:07 UTC, AlexCorn999 commented on internal/app/apiserver/apiserver.go
> +			auth.ID = newIDForDB + 1
Done ✅

2023-10-01 10:29 UTC, AlexCorn999 commented on internal/app/filestorage/filestorage.go
> +				return err
Done ✅

2023-10-03 16:15 UTC, merged